import os
import yaml
from ATACofthesnake import misc

# Read / set variables.
with open('Parameters.yaml') as f:
	paramDic = yaml.load(f, Loader=yaml.FullLoader)
Conditions = list(paramDic['Cond'])


localrules: checkindex, fragSize, BigWigs
rule all:
	input:
		expand(os.path.join(paramDic['Loc']['bamDir'], '{sample}.bam.bai'), sample=paramDic['Samples']),
		"deepTools/fragSizes.raw.tsv",
		"mergeBams/Merged.bam",
		'MACS2/Merged_peaks.narrowPeak',
		"diffAcc/counts.mat",
		"diffAcc/scaleFactors.txt",
		expand("BigWigs/{sample}.bw", sample=paramDic['Samples']),
		'deepTools/BigwigSum.npz',
		'Figures/plotCorr.png',
		"Figures/PCA.png",
		"deepTools/BigwigMatrix.gz",
		"Figures/Heatmap.png",
		"diffAcc/DESeq2.tsv"

rule checkIndex:
	input:
		'{sample}.bam'
	output:
		'{sample}.bam.bai'
	threads: 10
	shell:'''
	sambamba index -t {threads} {input}
	'''

rule fragSize:
	input:
		expand(os.path.join(paramDic['Loc']['bamDir'], '{sample}.bam.bai'), sample=paramDic['Samples'])
	output:
		"deepTools/fragSizes.raw.tsv"
	params:
		' '.join(expand(os.path.join(paramDic['Loc']['bamDir'], '{sample}.bam'), sample=paramDic['Samples']))
	threads: 10
	shell:'''
	echo {params}
	bamPEFragmentSize -b {params} -p {threads} --outRawFragmentLengths {output} 2> deepTools/fragSizes.err > deepTools/fragSizes.out
	'''
rule mergeBams:
	input:
		expand(os.path.join(paramDic['Loc']['bamDir'], '{sample}.bam.bai'), sample=paramDic['Samples'])
	output:
		"mergeBams/Merged.bam"
	params:
		' '.join(expand(os.path.join(paramDic['Loc']['bamDir'], '{sample}.bam'), sample=paramDic['Samples']))
	threads: 10
	shell:'''
	sambamba merge -t {threads} {output} {params}
	'''

rule MACS2:
	input:
		"mergeBams/Merged.bam"
	output:
		"MACS2/Merged_peaks.narrowPeak"
	params:
		genomeSize = paramDic['genomeSize'],
		outName = "Merged"
	threads: 1
	shell:'''
	macs2 callpeak -t {input} -f BAMPE --nomodel --nolambda -g {params.genomeSize} -n {params.outName} -p 0.01 --outdir MACS2/ --keep-dup all 2> MACS2/{params.outName}.log
	'''

rule countMat:
	input:
		"MACS2/Merged_peaks.narrowPeak"
	output:
		mat = "diffAcc/counts.mat",
		matnpz = "diffAcc/counts.npz"
	params:
		blackList = paramDic['blackList'],
		samples = ' '.join(expand(os.path.join(paramDic['Loc']['bamDir'], '{sample}.bam'), sample=paramDic['Samples']))
	threads: 20
	shell:'''
	multiBamSummary BED-file --BED {input} -bl {params.blackList} -p {threads} --outRawCounts {output.mat} -o {output.matnpz} -b {params.samples}
	# Remove quotes placed by multiBamSummary
	sed -i "s/'//g" diffAcc/counts.mat
	# Remove .bam postfix
	sed -i 's/\.bam//g' diffAcc/counts.mat
	'''

rule scaleFactors:
	input:
		"diffAcc/counts.mat"
	output:
		"diffAcc/scaleFactors.txt"
	threads: 1
	params:
		scriptLoc = os.path.join(paramDic["baseDir"], "Rscripts", "edgeR_scalefactors.R")
	shell:'''
	Rscript {params.scriptLoc} {input}
	'''

rule BigWigs:
	input:
		sf = "diffAcc/scaleFactors.txt",
		inFile = os.path.join(paramDic['Loc']['bamDir'], '{sample}.bam')
	output:
		"BigWigs/{sample}.bw"
	params:
		sampleName = '{sample}',
		blackList = paramDic['blackList'],
		genomeSize = paramDic['genomeSize']
	threads: 10
	shell:'''
	SCALEFAC=$(grep {params.sampleName} diffAcc/scaleFactors.txt | cut -f2 -d ' ')
	bamCoverage --scaleFactor $SCALEFAC -b {input.inFile} -o {output} -p {threads} -bs 25 --extendReads --ignoreDuplicates --effectiveGenomeSize {params.genomeSize} -bl {params.blackList}
	'''

rule multiBigwigSum:
	input:
		expand('BigWigs/{sample}.bw', sample=paramDic['Samples']),
		Peaks = "MACS2/Merged_peaks.narrowPeak"
	output:
		'deepTools/BigwigSum.npz'
	params:
		bigwigs = ' '.join(expand('BigWigs/{sample}.bw', sample=paramDic['Samples'])),
		blackList = paramDic['blackList'],
	threads: 10
	shell:'''
	multiBigwigSummary BED-file --BED {input.Peaks} -o {output} -b {params.bigwigs} -bl {params.blackList} -p {threads} -bs 150
	'''

rule plotCorr:
	input:
		"deepTools/BigwigSum.npz"
	output:
		"Figures/plotCorr.png"
	shell:'''
	plotCorrelation --corData {input} --corMethod pearson --whatToPlot heatmap --plotFile {output} --skipZeros -min 0.8 -max 1
	'''
rule plotPCA:
	input:
		"deepTools/BigwigSum.npz"
	output:
		"Figures/PCA.png"
	threads: 1
	shell:'''
	plotPCA --corData {input} -o {output} --transpose
	'''

rule computeMatrix:
	input:
		expand('BigWigs/{sample}.bw', sample=paramDic['Samples']),
	output:
		"deepTools/BigwigMatrix.gz"
	params:
		bigwigs = ' '.join(expand('BigWigs/{sample}.bw', sample=paramDic['Samples'])),
		bed = "TSS.bed"
	threads: 10
	shell:'''
	computeMatrix reference-point -S {params.bigwigs} -R {params.bed} --referencePoint center -a 2000 -b 2000 -out {output} -p {threads} --missingDataAsZero
	'''

rule plotHeatmap:
	input:
		"deepTools/BigwigMatrix.gz"
	output:
		"Figures/Heatmap.png"
	threads: 1
	shell:'''
	plotHeatmap -m {input}rrule -out {output} --refPointLabel TSS
	'''

rule DESeq2:
	input:
		"diffAcc/counts.mat"
	output:
		"diffAcc/DESeq2.tsv"
	params:
		scriptLoc = os.path.join(paramDic["baseDir"], "Rscripts", "DESeq2.R"),
		condOrder = misc.conditionsfromCount("diffAcc/counts.mat", paramDic['Cond'])
	threads: 1
	shell:'''
	Rscript {params.scriptLoc} {input} {params.condOrder}
	'''
