name: test_conda_envs
on: [push, pull_request]

jobs:
  list-envs:
    runs-on: ubuntu-latest
    outputs:
      env_files: ${{ steps.list_envs.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: List environment files
        id: list_envs
        run: |
          files=$(ls src/aos/rules/envs/*.yml | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$files" >> $GITHUB_OUTPUT

  create-conda-envs:
    needs: list-envs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_file: ${{ fromJson(needs.list-envs.outputs.env_files) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Miniconda (Miniforge)
        uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true

      - name: Create environment
        run: |
          mamba env create -f ${{ matrix.env_file }} -n test_env
